##############################################################################
## Example config for mbbx

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=1, HW_DESC=EL1018, SUBST_FILE=empty.substitutions"

## PLC 0: Test some mbbo and mbbi records
#$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=0, SAMPLE_RATE_MS=1000,FILE=./plc/mbbx.plc, PLC_MACROS='DBG=#,PLC_ID=0'")

## Load test mbbx records:
dbLoadRecords("mbbx.db","P=$(IOC):,PORT=MC_CPU1,TSE=0,T_SMP_MS=10")
