##############################################################################
## Example config for el3751 analog input

##############################################################################
require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=11, HW_DESC=EL3751, EC_RATE=500, NELM=${NELM=10}"

#- Range:
#- 0 = No range
#- 1 = +-30V
#- 2 = +-10V
#- 3 = ...
epicsEnvSet("ECMC_EC_SDO_INDEX",  "0x8000")
epicsEnvSet("ECMC_EC_SDO_INDEX_OFFSET",  "0x1")
epicsEnvSet("ECMC_EC_SDO_SIZE",          "2")
epicsEnvSet("ECMC_EC_SDO_VALUE",         "2")  # +-10V
ecmcConfigOrDie "Cfg.EcAddSdo(${ECMC_EC_SLAVE_NUM},${ECMC_EC_SDO_INDEX},$(ECMC_EC_SDO_INDEX_OFFSET),$(ECMC_EC_SDO_VALUE),$(ECMC_EC_SDO_SIZE))"

