##############################################################################
## Example config for el7037 modulo motion 

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}configureSlave.cmd, "SLAVE_ID=26, HW_DESC=EL7037, CONFIG=-Motor-Trinamic-QMot-QSH4218-41-10-035"

epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) $(ecmccfg_DIR)configureAxis.cmd, "CONFIG=./cfg/el7037_1_mod.ax"
#$(SCRIPTEXEC) $(ecmccfg_DIR)applyAxisSynchronization.cmd, "CONFIG=./cfg/el7037_1.sax"

$(SCRIPTEXEC) ($(ecmccfg_DIR)configureVirtualAxis.cmd, CONFIG=./cfg/el7037_2_mod.vax)
$(SCRIPTEXEC) ($(ecmccfg_DIR)applyAxisSynchronization.cmd, CONFIG=./cfg/el7037_2_mod.sax)
