##############################################################################
## Example config for el7037 positioning interface (no motorrecord support yet)

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}configureSlave.cmd, "SLAVE_ID=26, HW_DESC=EL7037_PosIF, CONFIG=-Motor-Trinamic-QMot-QSH4218-41-10-035"


# Below is a sequence describing what records to use for absolute positioning! 
#mcu002> dbpf IOC_TEST:m0s000-Pos01-StrtType 1
#mcu002> dbpf IOC_TEST:m0s000-Pos01-AccCmd 1000
#mcu002> dbpf IOC_TEST:m0s000-Pos01-DecCmd 1000
#mcu002> dbpf IOC_TEST:m0s000-Pos01-VelCmd 500
# Enable
#mcu002> dbpf IOC_TEST:m0s000-Drv01-Ctrl 1
# Move one rev (200step*64microstepping)
#mcu002> dbpf IOC_TEST:m0s000-Pos01-PosCmd 12800
#Trigg motion by toggle
#mcu002> dbpf IOC_TEST:m0s000-Pos01-Ctrl 0
#mcu002> dbpf IOC_TEST:m0s000-Pos01-Ctrl 1
# Get actual position alt 1
#mcu002> dbgf IOC_TEST:m0s000-Enc01-PosAct
# Get actual position alt 2
#mcu002> dbgf IOC_TEST:m0s000-Pos01-PosAct
# Stop motion
#mcu002> dbpf IOC_TEST:m0s000-Pos01-Ctrl 0

#- PVs:
#-IOC_TEST:m0s000-Enc01-Count
#-IOC_TEST:m0s000-Pos01-Ctrl
#-IOC_TEST:m0s000-Pos01-PosCmd
#-IOC_TEST:m0s000-Pos01-VelCmd
#-IOC_TEST:m0s000-Pos01-StrtType
#-IOC_TEST:m0s000-Pos01-AccCmd
#-IOC_TEST:m0s000-Pos01-DecCmd
#-IOC_TEST:m0s000-Drv01-Ctrl
#-IOC_TEST:m0s000-Enc01-Cmd
#-IOC_TEST:m0s000-Drv01-Stat
#-IOC_TEST:m0s000-Enc01-Stat
#-IOC_TEST:m0s000-Drv01-WrnAlrm
#-IOC_TEST:m0s000-Drv01-ErrAlrm
#-IOC_TEST:m0s000-Drv01-StlAlrm
#-IOC_TEST:m0s000-Drv01-SyncErrAlrm
#-IOC_TEST:m0s000-Enc01-OpnCrctAlrm
#-IOC_TEST:m0s000-Enc01-WrnAlrm
#-IOC_TEST:m0s000-Enc01-SyncErrAlrm
#-IOC_TEST:m0s000-Pos01-Stat
#-IOC_TEST:m0s000-Pos01-PosAct
#-IOC_TEST:m0s000-Pos01-Vel
#-IOC_TEST:m0s000-Pos01-Time
#-IOC_TEST:m0s000-Enc01-Count-RB
#-IOC_TEST:m0s000-Pos01-Ctrl-RB
#-IOC_TEST:m0s000-Pos01-PosCmd-RB
#-IOC_TEST:m0s000-Pos01-VelCmd-RB
#-IOC_TEST:m0s000-Pos01-StrtType-RB
#-IOC_TEST:m0s000-Pos01-AccCmd-RB
#-IOC_TEST:m0s000-Pos01-DecCmd-RB
#-IOC_TEST:m0s000-Drv01-Ctrl-RB
#-IOC_TEST:m0s000-Enc01-PosAct
#-IOC_TEST:m0s000-Enc01-LtchPosAct
#-IOC_TEST:m0s000-Enc01-Cmd-RB
