##############################################################################
## Example config for el3742
## Oversampling factor can be set by the changing the "NELM" arg to addSlave
## Note: The el3702 does not support any value of NELM. The EtherCAT bus period in nanoseconds diveded by 
##       oversampling factor must be an integer.  "(1/EC_RATE*1E9) / NELM" 
##       

##############################################################################
require ecmccfg

# Note NELM equals oversampling factor in this case
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=11, HW_DESC=EL3742, NELM=100"

ecmcConfigOrDie "Cfg.EcSelectReferenceDC(0,$(ECMC_EC_SLAVE_NUM))"

