##############################################################################
## Example config for el3602-0002
## Oversampling factor can be set by the changing the "NELM" arg to addSlave
##       

require ecmccfg v9.0.1_RC4 "IOC=$(IOC),ECMC_VER=v9.0.1_RC4, EC_RATE=1000"
require ecmccomp

##############################################################################
## Config hardware:

# Update records in 1ms (all data to EPICS in 1kHz)
epicsEnvSet(ECMC_SAMPLE_RATE_MS,1)

# Note NELM equals oversampling factor in this case
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=16, HW_DESC=ELM3602-0002, NELM=${NELM=50}"
${SCRIPTEXEC} ${ecmccfg_DIR}applyComponent.cmd "COMP=AI-Generic-Range,CH_ID=1,MACROS='RANGE=+-10V'"
${SCRIPTEXEC} ${ecmccfg_DIR}applyComponent.cmd "COMP=AI-Generic-Range,CH_ID=2,MACROS='RANGE=+-20mV'"

# Update records in 10ms (for all records loaded below)
epicsEnvSet(ECMC_SAMPLE_RATE_MS,10)

#Apply hardware configuration
ecmcConfigOrDie "Cfg.EcApplyConfig(1)"

##############################################################################
############# Configure diagnostics:

ecmcConfigOrDie "Cfg.EcSetDiagnostics(1)"
ecmcConfigOrDie "Cfg.EcEnablePrintouts(0)"
ecmcConfigOrDie "Cfg.EcSetDomainFailedCyclesLimit(100)"

##############################################################################
############# Go active:
$(SCRIPTEXEC) ($(ecmccfg_DIR)setAppMode.cmd)
