require ecmccfg "ENG_MODE=1,MASTER_ID=0"

# Hardware
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd,       "SLAVE_ID=14, HW_DESC=EL7041-0052"
${SCRIPTEXEC} ${ecmccfg_DIR}applyComponent.cmd  "COMP=Motor-Generic-2Phase-Stepper,MACROS='I_MAX_MA=1000,I_STDBY_MA=500,U_NOM_MV=48000,R_COIL_MOHM=1230,STEPS=400'"
epicsEnvSet("DRV_SLAVE", "${ECMC_EC_SLAVE_NUM}")

# Motion
${SCRIPTEXEC} ${ecmccfg_DIR}loadYamlAxis.cmd,    "FILE=./cfg/openloop.yaml,DEV=${IOC},DRV_SLAVE=${DRV_SLAVE}"
