##############################################################################
## Example config for el7211-0010

require ecmccfg, "EC_RATE=1000"

# Limit torque to 50% of motor rated torque
#- Rated current = 2710mA (see motor config file, "0x8011 0x12 Rated current (mA)")
#- Set to 50% of 2710 = 1355mA   (0x8011 0x11 Max current (mA))
epicsEnvSet("ECMC_EC_SLAVE_NUM_DRIVE",        "11")
${SCRIPTEXEC} ${ecmccfg_DIR}configureSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM_DRIVE), HW_DESC=EP7211-0034_ALL_FB, CONFIG=-Motor-Beckhoff-AM8111-0F20-0000,CFG_MACROS='I_MAX_MA=1355'"

epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) ($(ecmccfg_DIR)configureAxis.cmd, CONFIG=./cfg/el7201_1.ax)
