##############################################################################
## Example config for el3702
## Oversampling factor can be set by the changing the "NELM" arg to addSlave
## Note: The el3702 does not support any value of NELM. The EtherCAT bus period in nanoseconds diveded by 
##       oversampling factor must be an integer.  "(1/EC_RATE*1E9) / NELM" 
##       

require ecmccfg

# Ensure PV-update in 1Khz
epicsEnvSet("ECMC_SAMPLE_RATE_MS",            "1")
# Note NELM equals oversampling factor in this case
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=34, HW_DESC=EL3702, NELM=100"

ecmcConfigOrDie "Cfg.EcSelectReferenceDC(0,$(ECMC_EC_SLAVE_NUM))"

# Restore PV-update in 100Hz for less time critical records
epicsEnvSet("ECMC_SAMPLE_RATE_MS",            "10")

