##############################################################################
## Example config for el3162 analog input

##############################################################################
## Initiation:
epicsEnvSet("IOC" ,"$(IOC="IOC_TEST")")
epicsEnvSet("ECMCCFG_INIT" ,"")  #Only run startup once (auto at PSI, need call at ESS), variable set to "#" in startup.cmd
epicsEnvSet("SCRIPTEXEC" ,"$(SCRIPTEXEC="iocshLoad")")

require ecmccfg test_bk1250

# run module startup.cmd (only needed at ESS  PSI auto call at require)
$(ECMCCFG_INIT)$(SCRIPTEXEC) ${ecmccfg_DIR}startup.cmd, "IOC=$(IOC),ECMC_VER=6.0.2,EthercatMC_VER=3.0.2,stream_VER=2.8.10"

##############################################################################
## Config hardware:

epicsEnvSet("ECMC_EC_SLAVE_NUM",              "3")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), HW_DESC=BK1250"
epicsEnvSet("ECMC_KL_SLAVE_NUM",              "00")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlaveKL.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), SLAVE_ID_KL=$(ECMC_KL_SLAVE_NUM), HW_DESC=KL2032"
epicsEnvSet("ECMC_KL_SLAVE_NUM",              "01")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlaveKL.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), SLAVE_ID_KL=$(ECMC_KL_SLAVE_NUM), HW_DESC=KL1809"






#${SCRIPTEXEC} ../../../hardware/Beckhoff_couplers/ecmcBK1250.cmd
#epicsEnvSet("ECMC_KL_SLAVE_NUM",              "00")
#${SCRIPTEXEC} ../../../hardware/Beckhoff_slaves/ecmcKL2032.cmd
#epicsEnvSet("ECMC_KL_SLAVE_NUM",              "01")
#${SCRIPTEXEC} ../../../hardware/Beckhoff_slaves/ecmcKL1809.cmd

#Apply hardware configuration
ecmcConfigOrDie "Cfg.EcApplyConfig(1)"

##############################################################################
## PLC 0
#$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=0, SAMPLE_RATE_MS=1000,FILE=./plc/bk1250.plc")


##############################################################################
############# Configure diagnostics:

ecmcConfigOrDie "Cfg.EcSetDiagnostics(1)"
ecmcConfigOrDie "Cfg.EcEnablePrintouts(0)"
ecmcConfigOrDie "Cfg.EcSetDomainFailedCyclesLimit(100)"

# go active
$(SCRIPTEXEC) ($(ecmccfg_DIR)setAppMode.cmd)
