##############################################################################
## Example usefull to see ECMC perfromance
# Electrical Connections:
# 1. Connect signal generator to EL3702
# 2. Connect oscilloscope to signal generator and EL4732 output

# PLC Configs:
# 1. Transfer values directlly in PLC (ec_mm_cp())

##############################################################################
## Initiation:
epicsEnvSet("IOC" ,"$(IOC="IOC_TEST")")
epicsEnvSet("ECMCCFG_INIT" ,"")  #Only run startup once (auto at PSI, need call at ESS), variable set to "#" in startup.cmd
epicsEnvSet("SCRIPTEXEC" ,"$(SCRIPTEXEC="iocshLoad")")

require ecmccfg 8.0.0

# run module startup.cmd (only needed at ESS  PSI auto call at require)
$(ECMCCFG_INIT)$(SCRIPTEXEC) ${ecmccfg_DIR}startup.cmd, "IOC=$(IOC),ECMC_VER=8.0.0, EC_RATE=1000"

##############################################################################
## Config hardware:

epicsEnvSet("ECMC_SAMPLE_RATE_MS",            "${RATE="1"}")

# Choose sample rate (2, 10 or 100)
epicsEnvSet("ECMC_OVER_SMP",                  "${OVERSAMP="100"}")

# EL3702
epicsEnvSet("ECMC_EC_SLAVE_NUM_AI",           "62")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM_AI), HW_DESC=EL3702, NELM=${ECMC_OVER_SMP}"

# DC mode
rate)
epicsEnvSet("SYNC0_SHIFT",   "500000")           # Shift time 
ecmcConfigOrDie "Cfg.EcSlaveConfigDC(${ECMC_EC_SLAVE_NUM_AI},0x730,10000,${SYNC0_SHIFT=0},990000,0)"

# EL4732
epicsEnvSet("ECMC_EC_SLAVE_NUM_AO",           "63")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM_AO), HW_DESC=EL4732, NELM=${ECMC_OVER_SMP}"

# DC mode
epicsEnvSet("SYNC0_SHIFT",   "-500000")      # Shift time 
ecmcConfigOrDie "Cfg.EcSlaveConfigDC(${ECMC_EC_SLAVE_NUM_AO},0x730,10000,${SYNC0_SHIFT=0},990000,0)"


ecmcConfigOrDie "Cfg.EcSelectReferenceDC(0,$(ECMC_EC_SLAVE_NUM))"

#Apply hardware configuration
ecmcConfigOrDie "Cfg.EcApplyConfig(1)"

##############################################################################
## PLC 1
$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=1, SAMPLE_RATE_MS=${ECMC_SAMPLE_RATE_MS},FILE=./plc/moveData.plc")

##############################################################################
############# Configure diagnostics:

ecmcConfigOrDie "Cfg.EcSetDiagnostics(1)"
ecmcConfigOrDie "Cfg.EcEnablePrintouts(0)"
ecmcConfigOrDie "Cfg.EcSetDomainFailedCyclesLimit(100)"

# go active
$(SCRIPTEXEC) ($(ecmccfg_DIR)setAppMode.cmd)
