##############################################################################
## Example usefull to see ECMC perfromance
# Electrical Connections:
# 1. Connect signal generator to EL3702
# 2. Connect oscilloscope to signal generator and EL4732 output

# Epics Configs:
# 1. Read data form EL3702 in 100kHz (oversample factor 100 (optional 1,2,10,50,100)). 
# 2. Push data to EPICS waveform record (input)
# 3. Forward data to aclacout record configured to make maniplulations (gain and 
#    y-offset). Then forward record to output waveform   
# 4. output record linked to EL4732 analog output terminal
#
# Note: Values in wavform are in I/0 range units (+-32768 correspoinds to +-10V) . 
#       Offset value are in V
#       
##############################################################################

require ecmccfg
require calc 3.7.4

epicsEnvSet("ECMC_SAMPLE_RATE_MS",            "1")

# Choose sample rate (2, 10 or 100)
epicsEnvSet("ECMC_OVER_SMP",                  "${OVERSAMP="100"}")

# EL3702 (empty subst file => no default records loaded)
epicsEnvSet("ECMC_EC_SLAVE_NUM_AI",           "12")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM_AI), HW_DESC=EL3702, NELM=${ECMC_OVER_SMP}, SUBST_FILE=empty.substitutions"

# EL4732 (empty subst file => no default records loaded)
epicsEnvSet("ECMC_EC_SLAVE_NUM_AO",           "11")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM_AO), HW_DESC=EL4732, NELM=${ECMC_OVER_SMP}, SUBST_FILE=empty.substitutions"

ecmcConfigOrDie "Cfg.EcSelectReferenceDC(0,$(ECMC_EC_SLAVE_NUM))"

# Load custom records (no record loaded by addSlave.cmd)
dbLoadRecords(moveDataInEpics.db,"ECMC_P=${ECMC_PREFIX},PORT=${ECMC_ASYN_PORT},ADDR=0,TIMEOUT=1,MASTER_ID=${ECMC_EC_MASTER_ID},SLAVE_AI=${ECMC_EC_SLAVE_NUM_AI},SLAVE_AO=${ECMC_EC_SLAVE_NUM_AO},HWTYPE=${ECMC_EC_HWTYPE},T_SMP_MS=${ECMC_SAMPLE_RATE_MS},TSE=${ECMC_TSE}, NELM=${ECMC_OVER_SMP}")
