##############################################################################
## Example config for el6224 I/O link master WIP
## NOTE WIP!! Not working 100% yet

##############################################################################
## Initiation:
epicsEnvSet("IOC" ,"$(IOC="IOC_TEST")")
epicsEnvSet("ECMCCFG_INIT" ,"")  #Only run startup once (auto at PSI, need call at ESS), variable set to "#" in startup.cmd
epicsEnvSet("SCRIPTEXEC" ,"$(SCRIPTEXEC="iocshLoad")")

require ecmccfg develop

# run module startup.cmd (only needed at ESS  PSI auto call at require)
$(ECMCCFG_INIT)$(SCRIPTEXEC) ${ecmccfg_DIR}startup.cmd, "IOC=$(IOC),ECMC_VER=6.3.2"

##############################################################################
## Config hardware:

epicsEnvSet("ECMC_EC_SLAVE_NUM",              "11")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), HW_DESC=EL6224, SUBST_FILE=empty.substitutions"

# Example Panasonic-HG-C1100L3-P.cmd on CH 0
#-d    \pre ECMC_EC_CH_ID       01..04
epicsEnvSet("ECMC_EC_CH_ID",         "01")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL6224-Sensor-chX_Panasonic-HG-C1100L3-P.cmd

# Example default configuration of digital input CH 1
#-d    \pre ECMC_EC_CH_ID       01..04
epicsEnvSet("ECMC_EC_CH_ID",         "02")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL6224-Sensor-chX_input.cmd

# Example default configuration of digital input CH 2
#-d    \pre ECMC_EC_CH_ID       01..04
epicsEnvSet("ECMC_EC_CH_ID",         "03")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL6224-Sensor-chX_input.cmd

# Example default configuration of digital input CH 3
#-d    \pre ECMC_EC_CH_ID       01..04
epicsEnvSet("ECMC_EC_CH_ID",         "04")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL6224-Sensor-chX_input.cmd

#Apply hardware configuration
ecmcConfigOrDie "Cfg.EcApplyConfig(1)"

##############################################################################
## PLC 0
$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=0, SAMPLE_RATE_MS=100,FILE=./plc/el6224_Panasonic.plc, PLC_MACROS='PLC_ID=0,SLAVE_ID=$(ECMC_EC_SLAVE_NUM),DBG='")

##############################################################################
############# Configure diagnostics:

ecmcConfigOrDie "Cfg.EcSetDiagnostics(1)"
ecmcConfigOrDie "Cfg.EcEnablePrintouts(0)"
ecmcConfigOrDie "Cfg.EcSetDomainFailedCyclesLimit(100)"

# go active
$(SCRIPTEXEC) ($(ecmccfg_DIR)setAppMode.cmd)
