##############################################################################
## Example config for El1252

require ecmccfg

epicsEnvSet("ECMC_EC_SLAVE_NUM_1252",              "1")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM_1252), HW_DESC=EL1252"

epicsEnvSet("ECMC_EC_SLAVE_NUM_2252",              "3")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM_2252), HW_DESC=EL2252"

$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=1, SAMPLE_RATE_MS=1,FILE=./plc/offsetTime.plc, PLC_MACROS=',SLAVE_ID_EL1252=${ECMC_EC_SLAVE_NUM_1252},SLAVE_ID_EL2252=${ECMC_EC_SLAVE_NUM_2252}'")

