== drive

=== scaling

Denominator: {{ drive.denominator|default(1)|int }}

Numerator: {{ drive.numerator|default(0)|float }}

=== links

==== core functions

[cols="1,1"]
|===
|function | link

|control
|{{ drive.control }}

|status
|{{ drive.status }}

|setpoint
|{{ drive.setpoint }}

{%- if drive.reduceTorque %}
|reduced torque
|{{ drive.control }}.{{ drive.reduceTorque|int }}
{%- endif %}

{%- if drive.reset %}
|drive reset
|{{ drive.control }}.{{ drive.reset|int }}
{%- endif %}

{%- if drive.warning %}
|warning
|{{ drive.status }}.{{ drive.warning|int }}
{%- endif %}

{%- if drive.error %}
{%- for bit in drive.error %}
|error bit {{loop.index-1}}
|{{ drive.status }}.{{ bit|int }}
{%- endfor %}
{%- endif %}
|===

==== inputs

|===
|function | link

|limit forward
|{{ input.limit.forward }}

|limit backward
|{{ input.limit.backward }}

|home
|{{ input.home }}

|interlock
|{{ input.interlock }}
|===

{%- set output = None if output is not defined else output %}
{%if output.brake or output.health is defined%}
==== output

|===
|function | link

{%if output.brake is defined%}
|brake
|{{ output.brake|default('') }}
{%endif%}

{%if output.health is defined%}
|health
|{{ output.health|default('') }}
{%endif%}
|===
{%endif%}

=== brake
{%- set brake=None if drive.brake is not defined else drive.brake %}
{%if drive.brake is undefined%}
.Optional brake
NOTE: not defined
{%-else%}
{%if output.brake is undefined%}
WARNING: You forgot to define the output for the brake! +
Check the example below!
[source,yaml]
output:
  brake: 'ec0.s42.binaryOutput07'       # Ethercat entry for brake output

{%endif%}
.Timing
NOTE:   Brake will open *{{ brake.openDelay|default(0)|int }} cycles* after the amplifier powered up. +
        The brake will engage *{{ brake.closeAhead|default(0)|int }} cycles* ahead of powering down the amplifier.

CAUTION: Brakes are handled in EtherCAT cycles, rather than time!
{%endif%}
