##############################################################################
## Example config for el7031

#epicsEnvSet(IOC,c6025a)
require ecmccfg "ENG_MODE=1"

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=16, HW_DESC=EL5131_DC_TRG"
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=15, HW_DESC=EL4132"

## AXIS 1
#epicsEnvSet("DEV",      "$(IOC)")
${SCRIPTEXEC} ${ECMC_CONFIG_ROOT}loadYamlAxis.cmd, "FILE=cfg/axis.yaml,LIMIT=1000,TYPE=0"
