##############################################################################
## Example config for el7332 (2 ch dc motor driver)

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=3, HW_DESC=EL7332, SUBST_FILE=ecmcEL7332_volts.substitutions"

# Configure motor CH1
${SCRIPTEXEC} ${ecmccfg_DIR}applySlaveConfig.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), HW_DESC=EL7332, CONFIG=-ch1-Motor-MicroMotors-RH158.24.15"

# Configure motor CH2
${SCRIPTEXEC} ${ecmccfg_DIR}applySlaveConfig.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), HW_DESC=EL7332, CONFIG=-ch2-Motor-Maxon-115146"

#
# Test simple move without motion axis
# Enable drive (ch 1):
#   dbpf IOC_TEST:ec0-s3-EL7332-1-Drv-Cmd 1
#
# Set velocity (scaled in Volts since custom subsitution file):
#   dbpf IOC_TEST:ec0-s3-EL7332-1-Drv-Spd 5
#
