##############################################################################
## Example config for test of ethercat bus health ouput (digital output linked to status of bus) 

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=10, HW_DESC=EL2004"

# Test health output for ethercat status
ecmcConfigOrDie "Cfg.LinkEcEntryToObject(ec0.s$(ECMC_EC_SLAVE_NUM).binaryOutput04.0,ec0.health)"
