##############################################################################
## Example useful to see ECMC performance
# Electrical Connections:
# 1. Connect signal generator to EL3702
# 2. Connect oscilloscope to signal generator and EL4732 output

# PLC Configs:
# 1. Transfer values directly in PLC (ec_mm_cp())

require ecmccfg

epicsEnvSet("ECMC_SAMPLE_RATE_MS",            "${RATE="1"}")

# Choose sample rate (2, 10 or 100)
epicsEnvSet("ECMC_OVER_SMP",                  "${OVERSAMP="100"}")

# EK1101
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "HW_DESC=EK1101"
ecmcConfigOrDie "Cfg.EcSelectReferenceDC(0,${ECMC_EC_SLAVE_NUM})"
ecmcConfigOrDie "Cfg.EcSlaveConfigDC(${ECMC_EC_SLAVE_NUM},0x730,1000000,0,1000000,0)"

# EL4134
epicsEnvSet("ECMC_EC_SLAVE_NUM_AO",           "13")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM_AO), HW_DESC=EL4134"

# EL3174 +-10V
epicsEnvSet("ECMC_EC_SLAVE_NUM_AI",           "22")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM_AI), HW_DESC=EL3174_+-10V"

# PLC 1
$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=1, SAMPLE_RATE_MS=${ECMC_SAMPLE_RATE_MS},FILE=./plc/ai-to-ao.plc")

