##############################################################################
## Example config for el3162 analog input

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=9, HW_DESC=EL3162"

# Configure analog sensors common (filter settings valid for all channles)
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL3XXX-Sensor-common.cmd

# Configure analog sensors common (filter settings valid for all channles)
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL31XX-Sensor-common.cmd

# Example of default configuration of analog sensor CH0
epicsEnvSet("ECMC_EC_SDO_INDEX",         "0x8000")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL3162-Sensor-chX-default.cmd

# Example of default configuration of analog sensor CH1
epicsEnvSet("ECMC_EC_SDO_INDEX",         "0x8010")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL3162-Sensor-chX-default.cmd

