##############################################################################
## Example config for el4002 

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=30, HW_DESC=EL4002"

# Configure channel 1 with default values (just to show the available settings)
epicsEnvSet("ECMC_EC_SDO_INDEX",         "0x8000")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL4XXX-settings-chX-default.cmd

# Configure channel 2 with default values (just to show the available settings)
epicsEnvSet("ECMC_EC_SDO_INDEX",         "0x8010")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL4XXX-settings-chX-default.cmd
