##############################################################################
## Example config for el4102

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=13, HW_DESC=EL4102"

# Configure channel 1 with default values (just to show the available settings) NOTE: Strange that first ch is 8010 and not 8000 like similar terminals
epicsEnvSet("ECMC_EC_SDO_INDEX",         "0x8010")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL4XXX-settings-chX-default.cmd

# Configure channel 2 with default values (just to show the available settings)
epicsEnvSet("ECMC_EC_SDO_INDEX",         "0x8020")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL4XXX-settings-chX-default.cmd
