##############################################################################
## Example config for el4104

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=14, HW_DESC=EL4104"

# Configure channel 1 with default values (just to show the available settings)
epicsEnvSet("ECMC_EC_SDO_INDEX",         "0x8000")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL4XXX-settings-chX-default.cmd

# Configure channel 2 with default values (just to show the available settings)
epicsEnvSet("ECMC_EC_SDO_INDEX",         "0x8010")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL4XXX-settings-chX-default.cmd

# Configure channel 3 with default values (just to show the available settings)
epicsEnvSet("ECMC_EC_SDO_INDEX",         "0x8020")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL4XXX-settings-chX-default.cmd

# Configure channel 4 with default values (just to show the available settings)
epicsEnvSet("ECMC_EC_SDO_INDEX",         "0x8030")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL4XXX-settings-chX-default.cmd

