##############################################################################
## Generic configuration for any hardware slave. 
##
## Warning: No settings for motors or sensor will be performed!!!
##
## Mandatory arguments:
##  S_ID: Slave position on bus 
##  HW  : Slave type/name ("EL1018")
## 
## Example call: 
##  ESS (E3):  iocsh.bash genericTest.script "S_ID=10,HW=EL1018"
##  PSI EPICS: iocsh genericTest.script "S_ID=10,HW=EL1018"
##

require ecmccfg

epicsEnvSet("ECMC_EC_SLAVE_NUM",              $(S_ID="NOT_VALID"))
epicsEnvSet("ECMC_EC_SLAVE_DESC",             $(HW="NOT_VALID"))
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), HW_DESC=$(ECMC_EC_SLAVE_DESC)"

iocInit();

ecmcEpicsEnvSetCalc(DBGREP_STR, "${S_ID}", "%03d")

dbgrep *s${DBGREP_STR}*
epicsEnvUnset(DBGREP_STR)
