##############################################################################
#  See plcSyntaxHelp.plc for doc on commands.
#
#   NOTE 1: Assignment is ":=", equal is "="
#   NOTE 2: Each statement should be terminated with "|" (instaed of ";" since ";" is used as command delimiter)
#
#  Code Description:
#     1. Set interlock if trying to move passed ax1.enc.actpos>50|
#        Allow motion back again. NOTE: Better to use softlimits (same functionality)! 
#        This is just an exmple how the variables can be used.. 
#

#Create a new PLC
epicsEnvSet("ECMC_PLC_ID",        "0")

epicsEnvSet("ECMC_PLC_SAMPLE_RATE_MS","10") # execute in 100Hz
ecmcConfigOrDie "Cfg.CreatePLC(${ECMC_PLC_ID},${ECMC_PLC_SAMPLE_RATE_MS})"

#Add code
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  var blink_cycles:=1/plc0.scantime|         "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  var warning_light:=ec_chk_bit(ec0.s2.OUPIN_4,0)|       "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  ax1.traj.command:=10|                      "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  ax1.traj.cmddata:=3|                       "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  ax1.enc.homepos:=25|                       "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  ec0.s2.OUPIN_8 = ec_set_bit(ec0.s1.BI_1 and ax1.enc.actpos>0,0)|"
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  if(not(ax1.error))                         "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  {                                          "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=    ax1.drv.enable:=1|                       "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  }                                          "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  else                                       "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  {                                          "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=    ax1.reset:=1|                            "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  }|                                         "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  if(ax1.drv.enabled)                        "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  {                                          "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=    ax1.traj.execute:=1|                     "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  }|                                         "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  static.counter+=1|                         "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  if(static.counter>=blink_cycles)           "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  {                                          "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=    warning_light:=not(warning_light)|       "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=    static.counter:=0|                       "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=    plc0.error:=123|                         "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  }|                                         "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  if(ax1.enc.homed or ax1.error)             "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  {                                          "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=    ax1.traj.execute:=0|                     "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=    if(not(ax1.traj.busy))                   "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=    {                                        "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=      ax1.drv.enable:=0|                     "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=      plc0.enable:=0|                        "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=      plc0.error:=0|                         "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=      warning_light:=0|                      "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=    }|                                       "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  }|                                         "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  global.test:=warning_light|                "
ecmcConfigOrDie "Cfg.AppendPLCExpr(${ECMC_PLC_ID})=  ec0.s2.OUPIN_4:= ec_set_bit(warning_light,0)|"

#Enable PLC
ecmcConfigOrDie "Cfg.SetPLCEnable(${ECMC_PLC_ID},1)"
