############################################################
############# Example use of ASYN record to feed any ascii command to ecmc
#
# Simple test IOC for remote IOC access using Asyn record and 
# the ECMC comamnd "Cfg.IocshCmd=<ioccmd>"
#
# See last rows in this file for how to execute an example cmd
#
# Note: Unfortenately records cannot be loaded dynamically in EPICS
# 

##############################################################################
## Initiation:
epicsEnvSet("IOC" ,"$(IOC="IOC_TEST")")
epicsEnvSet("ECMCCFG_INIT" ,"")  #Only run startup once (auto at PSI, need call at ESS), variable set to "#" in startup.cmd
epicsEnvSet("SCRIPTEXEC" ,"$(SCRIPTEXEC="iocshLoad")")

require ecmccfg master

#- Choose motor record driver implementation
#-   ECMC_MR_MODULE="ecmcMotorRecord"  => ECMC native built in motor record support (Default)
#-   ECMC_MR_MODULE="EthercatMC"       => Motor record support from EthercatMC module (need to be loaded)
#- Uncomment the two lines below to use EthercatMC:
#- epicsEnvSet(ECMC_MR_MODULE,"EthercatMC")
#- require EthercatMC 3.0.2

# run module startup.cmd (only needed at ESS  PSI auto call at require)
$(ECMCCFG_INIT)$(SCRIPTEXEC) ${ecmccfg_DIR}startup.cmd, "IOC=$(IOC),ECMC_VER=master,stream_VER=2.8.10"

##############################################################################

$(SCRIPTEXEC) ($(ecmccfg_DIR)general.cmd 

##############################################################################
############# Example: 
#
# Commands to test iocshCmd over asyn record with ecmc ASCII command "Cfg.IocshCmd=<cmd>":
# 1: Set use of Binary output of Asyn record (to allow larger size than 40):
# caput -S IOC2:MCU-Cmd.OFMT "Binary"
# 2: Test simple dbl command (EPICS variables can be used also, ECMC_SLAVE_NUM):
# caput -S IOC2:MCU-Cmd.BOUT 'Cfg.IocshCmd=dbl'
# 3: Check response. Ends up in AINP since asyn input is set to ASCII (IFMT=ASCII) as default
# caget -S  IOC2:MCU-Cmd.AINP
