##############################################################################
## Example config for EL2068

require ecmccfg

##############################################################################
## Config hardware:

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=13, HW_DESC=EL2068"
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "HW_DESC=EL2819"

iocInit()

dbpf c6025a:m0s013-BO01 1
dbpf c6025a:m0s013-BO02 1
dbpf c6025a:m0s013-BO03 1
dbpf c6025a:m0s013-BO04 1
dbpf c6025a:m0s013-BO05 1
dbpf c6025a:m0s013-BO06 1
dbpf c6025a:m0s013-BO07 1
dbpf c6025a:m0s013-BO08 1

dbpf c6025a:m0s014-BO01 1
