${SCRIPTEXEC} ${ECMC_CONFIG_ROOT}${HW_DESC}.cmd

epicsEnvSet("ECMC_EC_CHANNEL"            "1")
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec$(ECMC_EC_MASTER_ID).s${ECMC_EC_SLAVE_NUM}.CH${ECMC_EC_CHANNEL}_PTO_CONTROL","asynInt32",$(ECMC_ASYN_SKIP_CYCLES))
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec$(ECMC_EC_MASTER_ID).s${ECMC_EC_SLAVE_NUM}.CH${ECMC_EC_CHANNEL}_VELOCITY_SETPOINT","asynInt32",$(ECMC_ASYN_SKIP_CYCLES))
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec$(ECMC_EC_MASTER_ID).s${ECMC_EC_SLAVE_NUM}.CH${ECMC_EC_CHANNEL}_ENC_CONTROL","asynInt32",$(ECMC_ASYN_SKIP_CYCLES))
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec$(ECMC_EC_MASTER_ID).s${ECMC_EC_SLAVE_NUM}.CH${ECMC_EC_CHANNEL}_VALUE","asynInt32",$(ECMC_ASYN_SKIP_CYCLES))
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec$(ECMC_EC_MASTER_ID).s${ECMC_EC_SLAVE_NUM}.CH${ECMC_EC_CHANNEL}_PTO_STATUS","asynUInt32Digital",$(ECMC_ASYN_SKIP_CYCLES))
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec$(ECMC_EC_MASTER_ID).s${ECMC_EC_SLAVE_NUM}.CH${ECMC_EC_CHANNEL}_ENC_STATUS","asynUInt32Digital",$(ECMC_ASYN_SKIP_CYCLES))
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec$(ECMC_EC_MASTER_ID).s${ECMC_EC_SLAVE_NUM}.CH${ECMC_EC_CHANNEL}_POSITION","asynInt32",$(ECMC_ASYN_SKIP_CYCLES))

epicsEnvSet("ECMC_EC_CHANNEL"            "2")
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec$(ECMC_EC_MASTER_ID).s${ECMC_EC_SLAVE_NUM}.CH${ECMC_EC_CHANNEL}_PTO_CONTROL","asynInt32",$(ECMC_ASYN_SKIP_CYCLES))
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec$(ECMC_EC_MASTER_ID).s${ECMC_EC_SLAVE_NUM}.CH${ECMC_EC_CHANNEL}_VELOCITY_SETPOINT","asynInt32",$(ECMC_ASYN_SKIP_CYCLES))
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec$(ECMC_EC_MASTER_ID).s${ECMC_EC_SLAVE_NUM}.CH${ECMC_EC_CHANNEL}_ENC_CONTROL","asynInt32",$(ECMC_ASYN_SKIP_CYCLES))
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec$(ECMC_EC_MASTER_ID).s${ECMC_EC_SLAVE_NUM}.CH${ECMC_EC_CHANNEL}_VALUE","asynInt32",$(ECMC_ASYN_SKIP_CYCLES))
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec$(ECMC_EC_MASTER_ID).s${ECMC_EC_SLAVE_NUM}.CH${ECMC_EC_CHANNEL}_PTO_STATUS","asynUInt32Digital",$(ECMC_ASYN_SKIP_CYCLES))
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec$(ECMC_EC_MASTER_ID).s${ECMC_EC_SLAVE_NUM}.CH${ECMC_EC_CHANNEL}_ENC_STATUS","asynUInt32Digital",$(ECMC_ASYN_SKIP_CYCLES))
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec$(ECMC_EC_MASTER_ID).s${ECMC_EC_SLAVE_NUM}.CH${ECMC_EC_CHANNEL}_POSITION","asynInt32",$(ECMC_ASYN_SKIP_CYCLES))

dbLoadTemplate("ecmcEL2522.substitutions","P=${ECMC_PREFIX}, PORT=${ECMC_ASYN_PORT}, ADDR=${ECMC_ASYN_ADDR}, TIMEOUT=${ECMC_ASYN_TIMEOUT}, MASTER_ID=${ECMC_EC_MASTER_ID}, SLAVE_POS=${ECMC_EC_SLAVE_NUM}, HWTYPE=${ECMC_EC_HWTYPE}")
