"${SCRIPTEXEC}" "${ECMC_CONFIG_ROOT}${HW_DESC}"
# Channel 1
ecmcAsynPortDriverAddParameter("${ECMC_ASYN_PORT}","ec${ECMC_EC_MASTER_ID}.s${ECMC_EC_SLAVE_NUM}.STATUS0","asynUInt32Digital","${ECMC_ASYN_SKIP_CYCLES}")
ecmcAsynPortDriverAddParameter("${ECMC_ASYN_PORT}","ec${ECMC_EC_MASTER_ID}.s${ECMC_EC_SLAVE_NUM}.POSITION0","asynInt32","${ECMC_ASYN_SKIP_CYCLES}")
# Channel 2
ecmcAsynPortDriverAddParameter("${ECMC_ASYN_PORT}","ec${ECMC_EC_MASTER_ID}.s${ECMC_EC_SLAVE_NUM}.STATUS1","asynUInt32Digital","${ECMC_ASYN_SKIP_CYCLES}")
ecmcAsynPortDriverAddParameter("${ECMC_ASYN_PORT}","ec${ECMC_EC_MASTER_ID}.s${ECMC_EC_SLAVE_NUM}.POSITION1","asynInt32","${ECMC_ASYN_SKIP_CYCLES}")

dbLoadTemplate("${ECMC_CONFIG_DB}ecmcEL5042.substitutions","P=${ECMC_PREFIX}, PORT=${ECMC_ASYN_PORT}, ADDR=${ECMC_ASYN_ADDR}, TIMEOUT=${ECMC_ASYN_TIMEOUT}, MASTER_ID=${ECMC_EC_MASTER_ID}, SLAVE_POS=${ECMC_EC_SLAVE_NUM}, HWTYPE=${ECMC_EC_HWTYPE}")
