$(SCRIPTEXEC) $(ECMC_CONFIG_ROOT)$(HW_DESC)

ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec${ECMC_EC_MASTER_ID}.s${ECMC_EC_SLAVE_NUM}.ENC_CONTROL","asynInt32",${ECMC_ASYN_SKIP_CYCLES})
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec${ECMC_EC_MASTER_ID}.s${ECMC_EC_SLAVE_NUM}.VALUE","asynInt32",${ECMC_ASYN_SKIP_CYCLES})
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec${ECMC_EC_MASTER_ID}.s${ECMC_EC_SLAVE_NUM}.ENC_STATUS","asynUInt32Digital",${ECMC_ASYN_SKIP_CYCLES})
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec${ECMC_EC_MASTER_ID}.s${ECMC_EC_SLAVE_NUM}.POSITION","asynInt32",${ECMC_ASYN_SKIP_CYCLES})
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec${ECMC_EC_MASTER_ID}.s${ECMC_EC_SLAVE_NUM}.LATCH_POSITION","asynInt32",${ECMC_ASYN_SKIP_CYCLES})
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec${ECMC_EC_MASTER_ID}.s${ECMC_EC_SLAVE_NUM}.FREQUENCY","asynInt32",${ECMC_ASYN_SKIP_CYCLES})
ecmcAsynPortDriverAddParameter(${ECMC_ASYN_PORT},"ec${ECMC_EC_MASTER_ID}.s${ECMC_EC_SLAVE_NUM}.PERIOD","asynInt32",${ECMC_ASYN_SKIP_CYCLES})

dbLoadRecords("${ECMC_CONFIG_DB}ecmcAsynGenericAnalogInput.db","P=${ECMC_PREFIX},PORT=${ECMC_ASYN_PORT},ADDR=${ECMC_ASYN_ADDR},TIMEOUT=${ECMC_ASYN_TIMEOUT},MASTER_ID=${ECMC_EC_MASTER_ID},SLAVE_POS=${ECMC_EC_SLAVE_NUM},HWTYPE=${ECMC_EC_HWTYPE},NAME=ec${ECMC_EC_MASTER_ID}.s${ECMC_EC_SLAVE_NUM}.FREQUENCY,REC_SUFFIX=Enc-FreqAct,TYPE=asynInt32")

dbLoadRecords("${ECMC_CONFIG_DB}ecmcAsynGenericAnalogInput.db","P=${ECMC_PREFIX},PORT=${ECMC_ASYN_PORT},ADDR=${ECMC_ASYN_ADDR},TIMEOUT=${ECMC_ASYN_TIMEOUT},MASTER_ID=${ECMC_EC_MASTER_ID},SLAVE_POS=${ECMC_EC_SLAVE_NUM},HWTYPE=${ECMC_EC_HWTYPE},NAME=ec${ECMC_EC_MASTER_ID}.s${ECMC_EC_SLAVE_NUM}.PERIOD,REC_SUFFIX=Enc-PeriodAct,TYPE=asynInt32")

dbLoadTemplate("${ECMC_CONFIG_DB}ecmcEL5101.substitutions","P=${ECMC_PREFIX}, PORT=${ECMC_ASYN_PORT}, ADDR=${ECMC_ASYN_ADDR}, TIMEOUT=${ECMC_ASYN_TIMEOUT}, MASTER_ID=${ECMC_EC_MASTER_ID}, SLAVE_POS=${ECMC_EC_SLAVE_NUM}, HWTYPE=${ECMC_EC_HWTYPE}")
