##############################################################################
## Test script to test that files and records loads like without errors for different hardwares.
## 
## WARNING: ETHERCAT BUS WILL NOT GO ONLINE. 
##          HARDWARE WILL NOT BE VERIFIED (ECMC_DEV_MODE=1)
##
## Mandatory arguments:
##  SLAVE_ID: Slave position on bus 
##  HW_DESC : Slave type/name ("EL1018")
## 
## Example call (test that EL1809 loads all files and records correct):
##  ESS (E3):  iocsh.bash genericTest.script SLAVE_ID=1 HW_DESC=EL1809
##
require ecmccfg

epicsEnvSet(ECMC_DEV_MODE, 1)  # Without verification and reset of slaves.

epicsEnvSet("ECMC_EC_SLAVE_NUM",              $(SLAVE_ID=0))
epicsEnvSet("ECMC_EC_SLAVE_DESC",             $(HW_DESC="NOT_VALID"))
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), HW_DESC=$(ECMC_EC_SLAVE_DESC)"

