##############################################################################
## Example config for el5002 

##############################################################################
require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=12, HW_DESC=EL5002"

# Configure Wachendorff encoder on channel 1
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL5002-Encoder-ch1-Wachendorff-WDGA36E-06-1218-SIA-B01-CB8.cmd
