##############################################################################
## Example config for el5002 

##############################################################################
require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=14, HW_DESC=EL5002"

# Configure Posital encoder on ch 1
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL5002-Encoder-ch1-Posital-OCD-S101G-1416-S060-PRL.cmd
