# ecmc test system
# Anders Sandström

require ecmccfg sandst_a "EC_RATE=500,MASTER_ID=1,ENG_MODE=1"
require ecmccomp sandst_a

epicsEnvSet("IOC" ,"$(IOC="c6025a")")
epicsEnvSet("SCRIPTEXEC" ,"$(SCRIPTEXEC="iocshLoad")")

# Configuration loaded via FoE
epicsEnvSet(DRV_ID,0)
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=${DRV_ID}, HW_DESC=Festo-CMMT-ST"
${SCRIPTEXEC} ${ecmccomp_DIR}applyComponent.cmd "COMP=Motor-Generic-2Phase-Stepper,MACROS='I_MAX_MA=500,I_STDBY_MA=200,L_COIL_UH=1330,R_COIL_MOHM=750,U_NOM_MV=24000,ROT_INERTIA_GCM2=50'"
${SCRIPTEXEC} ${ecmccomp_DIR}applyComponent.cmd "COMP=Encoder-RLS-LA11-26bit-BISS-C,MACROS='FORCE_CLK_FRQ_HZ=6000000,ST_BITS=12,MT_BITS=14,INV_DIR=1'"

##- ########### MUST BE LAST ##############
##- Reinit drive (seems it needs to be like this..)
#ecmcConfigOrDie "Cfg.EcWriteSdo(${DRV_ID},0x2003,0x1,1,1)"
#epicsThreadSleep 0.1
#ecmcConfigOrDie "Cfg.EcWriteSdo(${DRV_ID},0x2003,0x1,0,1)"
#ecmcConfigOrDie "Cfg.EcAddSdoDT(${DRV_ID},0x2003,0x1,1,S8)"

epicsEnvUnset(FESTO_TEMP_2)
epicsEnvUnset(FESTO_TEMP_1)
epicsEnvUnset(FESTO_TEMP)
epicsEnvUnset(FESTO_DONE)


ecmcConfigOrDie "Cfg.EcApplyConfig(1)"

# To check mode:
${SCRIPTEXEC} ${ecmccfg_DIR}addEcSdoRT.cmd, "SLAVE_ID=${DRV_ID},INDEX=0x6060,SUBINDEX=0x0,DT=U8,NAME=DrvMode"

# Configure Motion
epicsEnvSet("DEV",      "$(IOC)")
${SCRIPTEXEC} ${ECMC_CONFIG_ROOT}loadYamlAxis.cmd, "FILE=./cfg/axis_CSV_OL_OWIS_BISS.yaml"

# Other
ecmcConfigOrDie "Cfg.EcSetDiagnostics(1)"
ecmcConfigOrDie "Cfg.EcEnablePrintouts(0)"
ecmcConfigOrDie "Cfg.EcSetDomainFailedCyclesLimit(100)"
ecmcConfigOrDie "Cfg.SetDiagAxisIndex(1)"
ecmcConfigOrDie "Cfg.SetDiagAxisFreq(2)"
ecmcConfigOrDie "Cfg.SetDiagAxisEnable(0)"


# go active
$(SCRIPTEXEC) ($(ecmccfg_DIR)setAppMode.cmd)



iocInit()

