##############################################################################
## Example config ESS crate of type MCU1025

require ecmccfg

ecmcFileExist($(ecmccfg_DIR)ecmcMCU1025.cmd,1)
$(SCRIPTEXEC) $(ecmccfg_DIR)ecmcMCU1025.cmd

# ADDITIONAL SETUP
# Set all outputs to feed switches
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput01,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput02,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput03,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput04,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput05,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput06,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput07,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput08,1)"
# END of ADDITIONAL SETUP

## AXIS 1
epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) ($(ecmccfg_DIR)configureAxis.cmd, CONFIG=./cfg25/linear_1.ax)

iocInit()

# Some intressting PV:s
# IOC_TEST:Axis1-TgtPosCmd:
#   Target position for "MOVE_ABS" and "MOVE_REL"
# IOC_TEST:Axis1-TgtVelCmd
#   Target position for "MOVE_ABS" and "MOVE_REL"
# IOC_TEST:Axis1-EnaCmd
# IOC_TEST:Axis1-ExeCmd
# IOC_TEST:Axis1-RstCmd
# IOC_TEST:Axis1-MtnCmd
# IOC_TEST:Axis1-MtnCmdData
dbpf IOC_TEST:Axis1-TgtPosCmd 50
dbpf IOC_TEST:Axis1-TgtVelCmd 5
dbpf IOC_TEST:Axis1-EnaCmd 1

dbpf IOC_TEST:Axis1-MtnCmd MOVE_ABS
dbpf IOC_TEST:Axis1-MtnCmdData 0

# dbpf IOC_TEST:Axis1-ExeCmd 1
