##############################################################################
## Example config ESS crate of type MCU1021 with coupler instead of CPU
## Example to change motor record poll rate

##############################################################################
## Setting of poll rate must be done before call of startup.cmd (or require ecmccfg at psi)
# update period when not moving
epicsEnvSet(ECMC_MR_IDLE_POLL_MS,"1000")
# update period when moving
epicsEnvSet(ECMC_MR_MOV_POLL_MS,"200")

require ecmccfg

$(SCRIPTEXEC) $(ecmccfg_DIR)ecmcMCU1021_coupler.cmd

# ADDITIONAL SETUP
# Set all outputs to feed switches
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput01,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput02,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput03,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput04,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput05,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput06,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput07,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput08,1)"
# END of ADDITIONAL SETUP

## AXIS 1
epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) ($(ecmccfg_DIR)configureAxis.cmd, CONFIG=./cfg/linear_1.ax)

iocInit()

# Some intressting PV:s
# IOC_TEST:Axis1-TgtPosCmd:
#   Target position for "MOVE_ABS" and "MOVE_REL"
# IOC_TEST:Axis1-TgtVelCmd
#   Target position for "MOVE_ABS" and "MOVE_REL"
# IOC_TEST:Axis1-EnaCmd
# IOC_TEST:Axis1-ExeCmd
# IOC_TEST:Axis1-RstCmd
# IOC_TEST:Axis1-MtnCmd
# IOC_TEST:Axis1-MtnCmdData
dbpf IOC_TEST:Axis1-TgtPosCmd 10
dbpf IOC_TEST:Axis1-TgtVelCmd 5
dbpf IOC_TEST:Axis1-EnaCmd 1

dbpf IOC_TEST:Axis1-MtnCmd MOVE_ABS
dbpf IOC_TEST:Axis1-MtnCmdData 0

# dbpf IOC_TEST:Axis1-ExeCmd 1
