##############################################################################
## Example config for EL2522 step direction drive 

require ecmccfg


# Add output for enable of step direction drive (also to test reduce torque and brake)
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=2, HW_DESC=EL2808"
epicsEnvSet("ECMC_EC_SLAVE_NUM_OUTPUT",        "$(ECMC_EC_SLAVE_NUM)")

#Configure EL2521 as pulse direction
${SCRIPTEXEC} ${ecmccfg_DIR}configureSlave.cmd, "SLAVE_ID=11, HW_DESC=EL2522, CONFIG=-stepDirectionDrive"
epicsEnvSet("ECMC_EC_SLAVE_NUM_DRIVE",        "$(ECMC_EC_SLAVE_NUM)")

epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) ($(ecmccfg_DIR)configureAxis.cmd, CONFIG=./cfg/el2522_1.ax)

epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) ($(ecmccfg_DIR)configureAxis.cmd, CONFIG=./cfg/el2522_2.ax)
