#!/bin/sh

set -e

CAPUT="caput"
MOTOR=IOC_TEST:Axis1

$CAPUT $MOTOR.SPAM 1023
$CAPUT $MOTOR.DLY 0
$CAPUT $MOTOR.RTRY 3
$CAPUT $MOTOR.RMOD 2
$CAPUT $MOTOR.RDBL $MOTOR-PosAct
$CAPUT $MOTOR.RRES 0.95
$CAPUT $MOTOR.URIP 1
$CAPUT $MOTOR.TWF 1
