##############################################################################
## Example config for smaract MCS2

require ecmccfg v9.0.1_RC3,"IOC=$(IOC),ECMC_VER=sandst_a,EC_RATE=1000,MASTER_ID=1"
require ecmccomp sandst_a

##############################################################################
## Configure hardware

epicsEnvSet("MCS2_SLAVE_NUM",              "0")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(MCS2_SLAVE_NUM), HW_DESC=MCS2,"
${SCRIPTEXEC} ${ecmccomp_DIR}applyComponent.cmd "COMP=SmarAct-SLC1750ds,MACROS='HOME_VELO=1000'"
${SCRIPTEXEC} ${ecmccomp_DIR}applyComponent.cmd "COMP=SmarAct-SR2013s,CH_ID=2"

#Apply hardware configuration
ecmcConfigOrDie "Cfg.EcApplyConfig(1)"

##############################################################################
## AXIS 1 (MCS2 CH1)
#
epicsEnvSet("MCS2_CHID",              "1")
epicsEnvSet("DEV",      "$(IOC)")
#"-$(SCRIPTEXEC) ($(ecmccfg_DIR)configureAxis.cmd, CONFIG=./cfg/mcs2.ax)
${SCRIPTEXEC} ${ECMC_CONFIG_ROOT}loadYamlAxis.cmd, "FILE=./cfg/axis_lin.yaml"

##############################################################################
## AXIS 1 (MCS2 CH1)
#
epicsEnvSet("MCS2_CHID",              "2")
${SCRIPTEXEC} ${ECMC_CONFIG_ROOT}loadYamlAxis.cmd, "FILE=./cfg/axis_rot.yaml"

# Start in CSP
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${MCS2_SLAVE_NUM},mode01,8)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${MCS2_SLAVE_NUM},mode02,8)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${MCS2_SLAVE_NUM},mode03,8)"

##############################################################################
############# Configure diagnostics:

ecmcConfigOrDie "Cfg.EcSetDiagnostics(1)"
ecmcConfigOrDie "Cfg.EcEnablePrintouts(0)"
ecmcConfigOrDie "Cfg.EcSetDomainFailedCyclesLimit(100)"
#ecmcConfigOrDie "Cfg.SetDiagAxisIndex(1)"
#ecmcConfigOrDie "Cfg.SetDiagAxisFreq(2)"
ecmcConfigOrDie "Cfg.SetDiagAxisEnable(0)"

##############################################################################
############# go active:
$(SCRIPTEXEC) ($(ecmccfg_DIR)setAppMode.cmd)

iocInit()

dbgrep *s00${MCS2_SLAVE_NUM}*
