##############################################################################
## Example config for el7211-0010

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}configureSlave.cmd, "SLAVE_ID=40, HW_DESC=EL7211-0010, CONFIG=-Motor-Beckhoff-AM8121-0F00-0000"
epicsEnvSet("ECMC_EC_SLAVE_NUM_DRIVE",        "$(ECMC_EC_SLAVE_NUM)")


epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) ($(ecmccfg_DIR)configureAxis.cmd, CONFIG=./cfg/el7201_1.ax)
