##############################################################################
## Example config for sync a motor to system time.
## To be used togheter with mrf or ptp sync of system clock.

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}configureSlave.cmd, "SLAVE_ID=51, HW_DESC=EL7041-0052, CONFIG=-Motor-Amp-57TH76-4280"
epicsEnvSet("ECMC_EC_SLAVE_NUM_DRIVE",        "$(ECMC_EC_SLAVE_NUM)")

epicsEnvSet("ECMC_AXIS_TIME_NUM",              "1")
epicsEnvSet("ECMC_AXIS_PHASE_NUM",             "2")
epicsEnvSet("ECMC_AXIS_PHYS_NUM",              "3")

# AXIS 1 (timing system (dc time))
epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) ($(ecmccfg_DIR)configureVirtualAxis.cmd, CONFIG=./cfg/timing.vax)
$(SCRIPTEXEC) ($(ecmccfg_DIR)applyAxisSynchronization.cmd, CONFIG=./cfg/timing.sax)

# AXIS 1 (Phase)
epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) ($(ecmccfg_DIR)configureVirtualAxis.cmd, CONFIG=./cfg/phase.vax)
$(SCRIPTEXEC) ($(ecmccfg_DIR)applyAxisSynchronization.cmd, CONFIG=./cfg/phase.sax)

# AXIS 3 (physical right motor)
epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) ($(ecmccfg_DIR)configureAxis.cmd, CONFIG=./cfg/phys.ax)

ecmcConfigOrDie "Cfg.SetAxisAllowSourceChangeWhenEnabled(${ECMC_AXIS_PHYS_NUM},1)"

# PLC 0
$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=0, SAMPLE_RATE_MS=100,FILE=./plc/seq.plc,PLC_MACROS='AX_TIME=${ECMC_AXIS_TIME_NUM},AX_PHASE=${ECMC_AXIS_PHASE_NUM}, AX_PHYS=${ECMC_AXIS_PHYS_NUM}'")

iocInit()

dbpf $(IOC):timing.SPAM 0
dbpf $(IOC):phase.SPAM 0
dbpf $(IOC):phys.SPAM 0
