
require ecmccfg,sandst_a,"ECMC_VER=sandst_a,MASTER_ID=0"

# Configure hardware
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=1, HW_DESC=EL3004"
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=2, HW_DESC=EL5001"
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=3, HW_DESC=EL1008"
${SCRIPTEXEC} ${ecmccfg_DIR}configureSlave.cmd, "SLAVE_ID=4, HW_DESC=EL7031, CONFIG=-Motor-Trinamic-QMot-QSH4218-41-10-035"
epicsEnvSet(DRV_SID, ${ECMC_EC_SLAVE_NUM})
ecmcConfigOrDie "Cfg.EcApplyConfig(1)"

${SCRIPTEXEC} ${ecmccfg_DIR}loadMultiAxis.cmd, "FILE=./test.subst"

# go active
$(SCRIPTEXEC) $(ecmccfg_DIR)setAppMode.cmd

