##############################################################################
## Example config for el3604
## Oversampling factor can be set by the changing the "NELM" arg to addSlave
## This test script uses the +-320mV sensor configuration
## Scaling to engineering units are made in by plc:s and the result is 
## exposed to epics through data storages.
##
## Data storage have a 4 times larger size than the memmap so the callback 
## to epics will be less frequent (8ms based on 500Hz ec rate)
##
## The scaled data can be retrived in the data storage PVs: IOC_TEST:ds<dsId>-Data-Act  (dsId 0..3)
## Note the size of the arrays are 4 times the size of the oversampled data (callbacks 4 times less frequent).
##
## Example: EC_RATE=500Hz => oversampling size is 40 elements per sample. 
##          The data storages are 160 elements in size resulting in 
##          callbacks in 125Hz, or 8ms, for the data storages arrays.
##

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=0, HW_DESC=EK1100"

# Update records in 1ms (all data to EPICS in 500Hz)
epicsEnvSet(ECMC_SAMPLE_RATE_MS,2)

# Note NELM equals oversampling factor in this case. Use +-320mv Config file for all 4 channels
epicsEnvSet("NELM",              "40")
${SCRIPTEXEC} ${ecmccfg_DIR}configureSlave.cmd, "SLAVE_ID=11, HW_DESC=ELM3604, NELM=${NELM=20}, CONFIG=-Sensor_+-320mV"

# Update records in 10ms (for all records loaded below)
epicsEnvSet(ECMC_SAMPLE_RATE_MS,10)

# Make data storages 4 times the size of the memmaps
ecmcEpicsEnvSetCalc(DS_SIZE, "${NELM=20}*4")

$(SCRIPTEXEC) $(ecmccfg_DIR)addDataStorage.cmd "DS_ID=0, DS_SIZE=${DS_SIZE=20}, SAMPLE_RATE_MS=-1, DS_TYPE=0"
$(SCRIPTEXEC) $(ecmccfg_DIR)addDataStorage.cmd "DS_ID=1, DS_SIZE=${DS_SIZE=20}, SAMPLE_RATE_MS=-1, DS_TYPE=0"
$(SCRIPTEXEC) $(ecmccfg_DIR)addDataStorage.cmd "DS_ID=2, DS_SIZE=${DS_SIZE=20}, SAMPLE_RATE_MS=-1, DS_TYPE=0"
$(SCRIPTEXEC) $(ecmccfg_DIR)addDataStorage.cmd "DS_ID=3, DS_SIZE=${DS_SIZE=20}, SAMPLE_RATE_MS=-1, DS_TYPE=0"

##############################################################################
## Prepare PLC macros (check MM index and calc scale and offset):
ecmcConfig "EcGetMemMapId(ec0.s11.mm.analogInputArray01)"
epicsEnvSet(MM_CH_1,${ECMC_CONFIG_RETURN_VAL})
ecmcConfig "EcGetMemMapId(ec0.s11.mm.analogInputArray02)"
epicsEnvSet(MM_CH_2,${ECMC_CONFIG_RETURN_VAL})
ecmcConfig "EcGetMemMapId(ec0.s11.mm.analogInputArray03)"
epicsEnvSet(MM_CH_3,${ECMC_CONFIG_RETURN_VAL})
ecmcConfig "EcGetMemMapId(ec0.s11.mm.analogInputArray04)"
epicsEnvSet(MM_CH_4,${ECMC_CONFIG_RETURN_VAL})

# 24bit full range corresponds to +-343.600mV
ecmcEpicsEnvSetCalc(SCALE, "343.6/2^23;",%.10lf)
epicsEnvSet(OFFSET,0)

$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=0, SAMPLE_RATE_MS=-1,FILE=./plc/moveData.plc, PLC_MACROS='PLC_ID=0,DS_ID=0,MM_ID=${MM_CH_1},SCALE=${SCALE},OFFSET=${OFFSET}'")
$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=1, SAMPLE_RATE_MS=-1,FILE=./plc/moveData.plc, PLC_MACROS='PLC_ID=1,DS_ID=1,MM_ID=${MM_CH_2},SCALE=${SCALE},OFFSET=${OFFSET}'")
$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=2, SAMPLE_RATE_MS=-1,FILE=./plc/moveData.plc, PLC_MACROS='PLC_ID=2,DS_ID=2,MM_ID=${MM_CH_3},SCALE=${SCALE},OFFSET=${OFFSET}'")
$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=3, SAMPLE_RATE_MS=-1,FILE=./plc/moveData.plc, PLC_MACROS='PLC_ID=3,DS_ID=3,MM_ID=${MM_CH_4},SCALE=${SCALE},OFFSET=${OFFSET}'")

