##############################################################################
## Example config for el6224 I/O link master WIP
## NOTE WIP!! Not working 100% yet

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=11, HW_DESC=EL6224, SUBST_FILE=empty.substitutions"

# Example Panasonic-HG-C1100L3-P.cmd on CH 0
#-d    \pre ECMC_EC_CH_ID       01..04
epicsEnvSet("ECMC_EC_CH_ID",         "01")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL6224-Sensor-chX_Panasonic-HG-C1100L3-P.cmd

# Example default configuration of digital input CH 1
#-d    \pre ECMC_EC_CH_ID       01..04
epicsEnvSet("ECMC_EC_CH_ID",         "02")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL6224-Sensor-chX_input.cmd

# Example default configuration of digital input CH 2
#-d    \pre ECMC_EC_CH_ID       01..04
epicsEnvSet("ECMC_EC_CH_ID",         "03")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL6224-Sensor-chX_input.cmd

# Example default configuration of digital input CH 3
#-d    \pre ECMC_EC_CH_ID       01..04
epicsEnvSet("ECMC_EC_CH_ID",         "04")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL6224-Sensor-chX_input.cmd

$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=0, SAMPLE_RATE_MS=100,FILE=./plc/el6224_Panasonic.plc, PLC_MACROS='PLC_ID=0,SLAVE_ID=$(ECMC_EC_SLAVE_NUM),DBG='")

