##############################################################################
## Example config for el6224 I/O link master

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=1, HW_DESC=EL6224"

# Example of default configuration of digital input CH 0
#-d    \pre ECMC_EC_CH_ID       01..04
epicsEnvSet("ECMC_EC_CH_ID",         "01")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL6224-Sensor-chX_input.cmd

# Example of default configuration of digital input CH 1
#-d    \pre ECMC_EC_CH_ID       01..04
epicsEnvSet("ECMC_EC_CH_ID",         "02")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL6224-Sensor-chX_input.cmd

# Example of default configuration of digital input CH 2
#-d    \pre ECMC_EC_CH_ID       01..04
epicsEnvSet("ECMC_EC_CH_ID",         "03")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL6224-Sensor-chX_input.cmd

# Example of default configuration of digital input CH 3
#-d    \pre ECMC_EC_CH_ID       01..04
epicsEnvSet("ECMC_EC_CH_ID",         "04")
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL6224-Sensor-chX_input.cmd

$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=0, SAMPLE_RATE_MS=500,FILE=./plc/el6224_inputs.plc, PLC_MACROS='PLC_ID=0,SLAVE_ID=$(ECMC_EC_SLAVE_NUM),DBG='")

