##############################################################################
## Example config for el6224 I/O link master WIP
## NOTE WIP!! Not working 100% yet
##############################################################################
## Initiation:
epicsEnvSet("IOC" ,"$(IOC="IOC_TEST")")
epicsEnvSet("ECMCCFG_INIT" ,"")  #Only run startup once (auto at PSI, need call at ESS), variable set to "#" in startup.cmd
epicsEnvSet("SCRIPTEXEC" ,"$(SCRIPTEXEC="iocshLoad")")

require ecmccfg anders_sdo_complete

#- Choose motor record driver implementation
#-   ECMC_MR_MODULE="ecmcMotorRecord"  => ECMC native built in motor record support (Default)
#-   ECMC_MR_MODULE="EthercatMC"       => Motor record support from EthercatMC module (need to be loaded)
#- Uncomment the two lines below to use EthercatMC:
#- epicsEnvSet(ECMC_MR_MODULE,"EthercatMC")
#- require EthercatMC 3.0.2

# run module startup.cmd (only needed at ESS  PSI auto call at require)
$(ECMCCFG_INIT)$(SCRIPTEXEC) ${ecmccfg_DIR}startup.cmd, "IOC=$(IOC),ECMC_VER=anders_sdo_complete,stream_VER=2.8.10"

##############################################################################
## Config hardware:

epicsEnvSet("ECMC_EC_SLAVE_NUM",              "1")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ECMC_EC_SLAVE_NUM), HW_DESC=EL6224"

#- <PS>;CoE;0x1A00 C 0;01 00 20 01 00 60;download pdo 0x1A00 entries
ecmcConfigOrDie "Cfg.EcAddSdoComplete(${ECMC_EC_SLAVE_NUM},0x1A00, 01 00 20 01 00 60,6)"
#- <PS>;CoE;0x1A01 C 0;03 00 01 01 10 60 07 00 00 00 08 00 00 00;download pdo 0x1A01 entries
ecmcConfigOrDie "Cfg.EcAddSdoComplete(${ECMC_EC_SLAVE_NUM},0x1A01,03 00 01 01 10 60 07 00 00 00 08 00 00 00,14)"
#- <PS>;CoE;0x1A02 C 0;03 00 01 01 20 60 07 00 00 00 08 00 00 00;download pdo 0x1A02 entries
ecmcConfigOrDie "Cfg.EcAddSdoComplete(${ECMC_EC_SLAVE_NUM},0x1A02,03 00 01 01 20 60 07 00 00 00 08 00 00 00,14)"
#- <PS>;CoE;0x1A03 C 0;03 00 01 01 30 60 07 00 00 00 08 00 00 00;download pdo 0x1A03 entries
ecmcConfigOrDie "Cfg.EcAddSdoComplete(${ECMC_EC_SLAVE_NUM},0x1A03,03 00 01 01 30 60 07 00 00 00 08 00 00 00,14)"
#- <PS>;CoE;0x1C12 C 0;00 00;download pdo 0x1C12 index
ecmcConfigOrDie "Cfg.EcAddSdoComplete(${ECMC_EC_SLAVE_NUM},0x1C12,00 00,2)"
#- <PS>;CoE;0x1C13 C 0;05 00 04 1A 00 1A 01 1A 02 1A 03 1A;download pdo 0x1C13 index
ecmcConfigOrDie "Cfg.EcAddSdoComplete(${ECMC_EC_SLAVE_NUM},0x1C13,05 00 04 1A 00 1A 01 1A 02 1A 03 1A,12)"

#- PS;CoE;0x8000 C 1;02 80 02 00 42 03 00 00 11 2B 0A 00 C3 00 00 00 00 00 23 00;Object 8000
#ecmcConfigOrDie "Cfg.EcAddSdoBuffer(${ECMC_EC_SLAVE_NUM},0x8000,0x01,02 80 02 00 42 03 00 00 11 2B 0A 00 C3 00 00 00 00 00 23 00,20)"
#- PS;CoE;0x8010 C 1;00 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00 00 01 00;Object 8010
#ecmcConfigOrDie "Cfg.EcAddSdoBuffer(${ECMC_EC_SLAVE_NUM},0x8010,0x01,02 80 02 00 42 03 00 00 11 2B 0A 00 C3 00 00 00 00 00 23 00,20)"
#- PS;CoE;0x8020 C 1;00 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00 00 01 00;Object 8020
#ecmcConfigOrDie "Cfg.EcAddSdoBuffer(${ECMC_EC_SLAVE_NUM},0x8020,0x01,02 80 02 00 42 03 00 00 11 2B 0A 00 C3 00 00 00 00 00 23 00,20)"
#- PS;CoE;0x8030 C 1;00 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 00 00 01 00;Object 8030
#ecmcConfigOrDie "Cfg.EcAddSdoBuffer(${ECMC_EC_SLAVE_NUM},0x8030,0x01,02 80 02 00 42 03 00 00 11 2B 0A 00 C3 00 00 00 00 00 23 00,20)"


#Apply hardware configuration
ecmcConfigOrDie "Cfg.EcApplyConfig(1)"

##############################################################################
############# Configure diagnostics:

ecmcConfigOrDie "Cfg.EcSetDiagnostics(1)"
ecmcConfigOrDie "Cfg.EcEnablePrintouts(0)"
ecmcConfigOrDie "Cfg.EcSetDomainFailedCyclesLimit(100)"

# go active
$(SCRIPTEXEC) ($(ecmccfg_DIR)setAppMode.cmd)
