##############################################################################
## Example config for smaract MCS2

require ecmccfg, "IOC=$(IOC),EC_RATE=1000,MASTER_ID=0,ENG_MODE=1"

${SCRIPTEXEC} ${ecmccfg_DIR}setRecordUpdateRate.cmd "RATE_MS=1"

epicsEnvSet("MCS2_SLAVE_NUM",              "15")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(MCS2_SLAVE_NUM), HW_DESC=MCS2,"
${SCRIPTEXEC} ${ecmccfg_DIR}applyComponent.cmd "COMP=SmarAct-SLC1750ds,MACROS='HOME_VELO=1000,HOME_ACC=1000'"
${SCRIPTEXEC} ${ecmccfg_DIR}applyComponent.cmd "COMP=SmarAct-SR2013s,CH_ID=2"
${SCRIPTEXEC} ${ecmccfg_DIR}applyComponent.cmd "COMP=SmarAct-SR2013s,CH_ID=3,MACROS='HOME_VELO=10000,HOME_ACC=1000'"

# AXIS 1 (MCS2 CH1)
epicsEnvSet("MCS2_CHID",              "1")
epicsEnvSet("DEV",      "$(IOC)")
${SCRIPTEXEC} ${ECMC_CONFIG_ROOT}loadYamlAxis.cmd, "FILE=./cfg/axis_lin.yaml"

# AXIS 3 (MCS2 CH1)
epicsEnvSet("MCS2_CHID",              "3")
${SCRIPTEXEC} ${ECMC_CONFIG_ROOT}loadYamlAxis.cmd, "FILE=./cfg/axis_rot.yaml"
