default: help
help ::
	@echo "====================================================================================="
	@echo "available targets for IOC installation"
	@echo " -> make install      to install c6025a-08"
        
install ::	
	ioc install --clean -V --ioc MTEST04-MTN-ASM
