##############################################################################
## Example config for elm3148
## Oversampling factor can be set by the changing the "NELM" arg to addSlave
##       

require ecmccfg sandst_a "IOC=$(IOC),EC_RATE=500"
require ecmccomp

##############################################################################
## Config hardware:

# Update records in 1ms (all data to EPICS in 1kHz)
epicsEnvSet(ECMC_SAMPLE_RATE_MS,2)

# Note NELM equals oversampling factor in this case
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=16, HW_DESC=ELM3148,NELM=2"

# Update records in 10ms (for all records loaded below)
epicsEnvSet(ECMC_SAMPLE_RATE_MS,10)

#Apply hardware configuration
ecmcConfigOrDie "Cfg.EcApplyConfig(1)"

##############################################################################
############# Configure diagnostics:

ecmcConfigOrDie "Cfg.EcSetDiagnostics(1)"
ecmcConfigOrDie "Cfg.EcEnablePrintouts(0)"
ecmcConfigOrDie "Cfg.EcSetDomainFailedCyclesLimit(100)"

##############################################################################
############# Go active:
$(SCRIPTEXEC) $(ecmccfg_DIR)setAppMode.cmd
