##############################################################################
## Example config for elm3146
## Oversampling factor can be set by the changing the "NELM" arg to addSlave
##       

require ecmccfg, "IOC=$(IOC),EC_RATE=1000"

# Update records in 1ms (all data to EPICS in 1kHz)
epicsEnvSet(ECMC_SAMPLE_RATE_MS,1)

# Note NELM equals oversampling factor in this case
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=15, HW_DESC=ELM3146,NELM=1"

# Update records in 10ms (for all records loaded below)
epicsEnvSet(ECMC_SAMPLE_RATE_MS,10)

