##############################################################################
## Example config for elm3146
## Oversampling factor can be set by the changing the "NELM" arg to addSlave
##       

require ecmccfg v11.0.0_RC1, "EC_RATE=1000,ECMC_VER=v11.0.0_RC1"

# Update records in 1ms (all data to EPICS in 1kHz)
epicsEnvSet(ECMC_SAMPLE_RATE_MS,1)

# Note NELM equals oversampling factor in this case
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=11, HW_DESC=ELM3146,NELM=1"

# Note NELM equals oversampling factor in this case
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=12, HW_DESC=ELM3004,NELM=1"

# Update records in 10ms (for all records loaded below)
epicsEnvSet(ECMC_SAMPLE_RATE_MS,10)

