##############################################################################
## Example config ESS crate of type MCU1021_coupler with test of auto on off

require ecmccfg
require autosave 5.10.0

## Configure hardware:
ecmcFileExist($(ecmccfg_DIR)ecmcMCU1021_coupler.cmd,1)
$(SCRIPTEXEC) $(ecmccfg_DIR)ecmcMCU1021_coupler.cmd

# ADDITIONAL SETUP
# Set all outputs to feed switches
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput01,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput02,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput03,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput04,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput05,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput06,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput07,1)"
ecmcConfigOrDie "Cfg.WriteEcEntryIDString(${ECMC_EC_SLAVE_NUM_DIG_OUT},binaryOutput08,1)"
# END of ADDITIONAL SETUP

## AXIS 1
epicsEnvSet(ECMC_ENC_SLAVE_ID,3)
epicsEnvSet(ECMC_ENC_CH_ID,1)
epicsEnvSet(ECMC_ENC_TYPE,0)      # Type: 0=Incremental, 1=Absolute
epicsEnvSet(ECMC_DRV_SLAVE_ID,8)

epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) ($(ecmccfg_DIR)configureAxis.cmd, CONFIG=./cfg/linear_1_auto_on_off.ax)

## AXIS 2
epicsEnvSet(ECMC_ENC_SLAVE_ID,4)
epicsEnvSet(ECMC_ENC_CH_ID,1)
epicsEnvSet(ECMC_ENC_TYPE,0)      # Type: 0=Incremental, 1=Absolute
epicsEnvSet(ECMC_DRV_SLAVE_ID,9)

epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) ($(ecmccfg_DIR)configureAxis.cmd, CONFIG=./cfg/linear_2_no_auto.ax)

