##############################################################################
## 1. Example ecmc PLC varaible to external record
## 2. Example external record to ecmc PLC varaible

require ecmccfg

##############################################################################
## PLC 
$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=0, SAMPLE_RATE_MS=1000,FILE=./plc/external.plc"
dbLoadRecords("external.db","P=$(IOC):,PORT=MC_CPU1,T_SMP_MS=1000")

#### Use to monitor records
# camonitor IOC_TEST:FromPLC IOC_TEST:FromExternal IOC_TEST:ToPLC IOC_TEST:ToExternal

#### set data of external system  
# caput IOC_TEST:FromExternal 10
