##############################################################################
## Example config for el7041

epicsEnvSet(IOC,c6025a)
require ecmccfg PVT "ECMC_VER=PVT,ENG_MODE=1,MAX_PARAM_COUNT=1000"

# Load components lib
require ecmccomp

##############################################################################
## Configure hardware

#-epicsEnvSet("ENC_SLAVE_1",          "2")
#-${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ENC_SLAVE_1), HW_DESC=EL5001"
#-${SCRIPTEXEC} ${ecmccomp_DIR}applyComponent.cmd "COMP=Encoder-RLS-LA11-24bit-SSI,CH_ID=1"

epicsEnvSet("DRV_SLAVE",              "13")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(DRV_SLAVE), HW_DESC=EL7041-0052"
${SCRIPTEXEC} ${ecmccomp_DIR}applyComponent.cmd "COMP=Motor-Generic-2Phase-Stepper,MACROS='I_MAX_MA=1000,I_STDBY_MA=500,U_NOM_MV=48000,R_COIL_MOHM=1230,STEPS=400'"

epicsEnvSet("ENC_SLAVE_2",            "14")
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ENC_SLAVE_2), HW_DESC=EL5042"
${SCRIPTEXEC} ${ecmccomp_DIR}applyComponent.cmd "COMP=Encoder-RLS-LA11-24bit-BISS-C,CH_ID=1"
${SCRIPTEXEC} ${ecmccomp_DIR}applyComponent.cmd "COMP=Encoder-RLS-LA11-24bit-BISS-C,CH_ID=2"

#-epicsEnvSet("ENC_SLAVE_3",            "15")
#-${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=$(ENC_SLAVE_3), HW_DESC=EL5002"
#-${SCRIPTEXEC} ${ecmccomp_DIR}applyComponent.cmd "COMP=Encoder-RLS-LA11-24bit-SSI,CH_ID=1"
#-${SCRIPTEXEC} ${ecmccomp_DIR}applyComponent.cmd "COMP=Encoder-RLS-LA11-24bit-SSI,CH_ID=2"

#Apply hardware configuration
ecmcConfigOrDie "Cfg.EcApplyConfig(1)"


#asynSetTraceMask(${ECMC_ASYN_PORT}, -1, 0xFF)
#asynSetTraceIOMask(${ECMC_ASYN_PORT}, -1, 0xFF)
#asynSetTraceInfoMask(${ECMC_ASYN_PORT}, -1, 0xFF)
#ecmcConfigOrDie "Cfg.SetTraceMaskBit(15,1)"



##############################################################################
## AXIS 1
#
epicsEnvSet("DEV",      "$(IOC)")
epicsEnvSet("PLC_PATH",      "/ioc/c6025a/ecmccfg/examples/test/ecmccomp/plc/")
${SCRIPTEXEC} ${ECMC_CONFIG_ROOT}loadYamlAxis.cmd, "FILE=./cfg/axis_pvt.yaml"

##############################################################################
## PVT controller: Call after axes are configured in order to use default values configured in axes configs
#

${SCRIPTEXEC} ${ECMC_CONFIG_ROOT}pvtControllerConfig.cmd

##############################################################################
############# Configure diagnostics:

ecmcConfigOrDie "Cfg.EcSetDiagnostics(1)"
ecmcConfigOrDie "Cfg.EcEnablePrintouts(0)"
ecmcConfigOrDie "Cfg.EcSetDomainFailedCyclesLimit(100)"
ecmcConfigOrDie "Cfg.SetDiagAxisIndex(1)"
ecmcConfigOrDie "Cfg.SetDiagAxisFreq(2)"
ecmcConfigOrDie "Cfg.SetDiagAxisEnable(0)"

# go active
$(SCRIPTEXEC) ($(ecmccfg_DIR)setAppMode.cmd)

#- ecmcConfig "Cfg.SetAxisErrorId(1,100000)"


#asynSetTraceMask(${ECMC_ASYN_PORT}, -1, 0x41)
#asynSetTraceIOMask(${ECMC_ASYN_PORT}, -1, 6)
#asynSetTraceInfoMask(${ECMC_ASYN_PORT}, -1, 1)
#ecmcConfigOrDie "Cfg.SetTraceMaskBit(15,1)"


