##############################################################################
## Example config for el7041

epicsEnvSet(IOC,c6025a)
require ecmccfg PVT "ECMC_VER=PVT,ENG_MODE=1,MAX_PARAM_COUNT=1000"

# Load components lib
require ecmccomp

#- ############################################################################
#- add slaves
#- list of slaves (4 axis test motion box)
# Master0
#    0  0:0   PREOP  +  EK1100 EtherCAT-Koppler (2A E-Bus)
#    1  0:1   PREOP  +  EL5001 1K. SSI Encoder
#    2  0:2   PREOP  +  EL5131 1Ch. Inc. Encoder 5V (RS422,TTL), 2x24V DC Output
#    3  0:3   PREOP  +  EL4132 2Ch. Ana. Ausgang +/-10V, 16bit
#    4  0:4   PREOP  +  EL7031 1K. Schrittmotor-Endstufe (24V, 1.5A)
#    5  0:5   PREOP  +  EL7342 2K. DC-Motor-Endstufe (50V, 3.5A)
#    6  0:6   PREOP  +  EL2008 8K. Dig. Ausgang 24V, 0.5A
#    7  0:7   PREOP  +  EL6224 (IO Link Master)
#    8  0:8   PREOP  +  EL4732 2K. Ana. Ausgang +/-10V, Oversample
#    9  0:9   PREOP  +  EL3702 2K. Ana. Eingang +/-10V, DIFF, Oversample
#   10  0:10  PREOP  +  EL2819 16K. Dig. Ausgang 24V, 0,5A, Diagnose
#   11  0:11  PREOP  +  EL2068 8Ch. Dig Output 24V, 0.5A
#   12  0:12  PREOP  +  EL7201 1K. MDP742 Servo-Motor-Endstufe (50V, 4A)
#   13  0:13  PREOP  +  EL7041-0052 1Ch. Stepper motor output stage (50V, 5A)
#   14  0:14  PREOP  +  EL5042 2Ch. BiSS-C Encoder
#   15  0:15  PREOP  +  ELM3146-0000 6Ch. Ana. Input +/-10V, +/-20mA, 24 bit, high prec
# 
# 0:13 - EL7041    1Ch Stepper
${SCRIPTEXEC} ${ECMC_CONFIG_ROOT}addSlave.cmd,     "SLAVE_ID=13,HW_DESC=EL7041-0052"
${SCRIPTEXEC} ${ecmccomp_DIR}applyComponent.cmd    "COMP=Motor-Generic-2Phase-Stepper,MACROS='I_MAX_MA=1000,I_STDBY_MA=500,U_NOM_MV=48000,R_COIL_MOHM=1230,STEPS=400'"
epicsEnvSet("DRV_SLAVE",      "$(ECMC_EC_SLAVE_NUM)")

#- #################################################################
#- apply the configuration
${SCRIPTEXEC} ${ECMC_CONFIG_ROOT}applyConfig.cmd

##############################################################################
## AXIS 1
#

epicsEnvSet("DEV",      "$(IOC)")
epicsEnvSet("PLC_PATH",      "/ioc/c6025a/ecmccfg/examples/test/ecmccomp/plc/")
${SCRIPTEXEC} ${ECMC_CONFIG_ROOT}loadYamlAxis.cmd, "FILE=./cfg/axis_pvt_hw2.yaml"

##############################################################################
## PVT controller: Call after axes are configured in order to use default values configured in axes configs
#

${SCRIPTEXEC} ${ECMC_CONFIG_ROOT}pvtControllerConfig.cmd

##############################################################################
## Load plugin: MOTION
# bash startGui.sh MTEST04-MTN-ASM 0 "/tmp"
epicsEnvSet(ECMC_PLUGIN_CONFIG,"PLUGIN_ID=1,AX=1,BUFF_SIZE=200,DBG=0,ENA=1")
require ecmc_plugin_motion sandst_a "${ECMC_PLUGIN_CONFIG}"

##############################################################################
############# Configure diagnostics:

ecmcConfigOrDie "Cfg.EcSetDiagnostics(1)"
ecmcConfigOrDie "Cfg.EcEnablePrintouts(0)"
ecmcConfigOrDie "Cfg.EcSetDomainFailedCyclesLimit(100)"
ecmcConfigOrDie "Cfg.SetDiagAxisIndex(1)"
ecmcConfigOrDie "Cfg.SetDiagAxisFreq(2)"
ecmcConfigOrDie "Cfg.SetDiagAxisEnable(0)"

# go active
$(SCRIPTEXEC) ($(ecmccfg_DIR)setAppMode.cmd)

#- ecmcConfig "Cfg.SetAxisErrorId(1,100000)"


#asynSetTraceMask(${ECMC_ASYN_PORT}, -1, 0x41)
#asynSetTraceIOMask(${ECMC_ASYN_PORT}, -1, 6)
#asynSetTraceInfoMask(${ECMC_ASYN_PORT}, -1, 1)
#ecmcConfigOrDie "Cfg.SetTraceMaskBit(15,1)"


