co##############################################################################
## Example config for el7037 and use of CFG_MACROS for:
## 1. configureSlave.cmd   (Set currents)
## 2. configureAxis.cmd   (Set axisId)

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}configureSlave.cmd, "SLAVE_ID=8, HW_DESC=EL7037, CONFIG=-Motor-Nanotec-ST4118L1804-B, CFG_MACROS='I_RUN_MA=900,I_STDBY_MA=200'"

## AXIS 5 Configuration macros for axis id (AXIS_ID)
#
epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) $(ecmccfg_DIR)configureAxis.cmd, "CONFIG=./cfg/el7037_x.ax, CFG_MACROS='AXIS_ID=5'"

