##############################################################################
## Example config for el7041-0052 

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}configureSlave.cmd, "SLAVE_ID=37, HW_DESC=EL7041-0052, CONFIG=-Motor-OrientalMotor-PK296DB"
epicsEnvSet("ECMC_EC_SLAVE_NUM_DRIVE","$(ECMC_EC_SLAVE_NUM)")

epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) ($(ecmccfg_DIR)configureAxis.cmd, CONFIG=./cfg/el704X_1.ax)
