##############################################################################
## Example config for iPOS8020 closed loop, scaling in mm (10mm/rev)
## Resolver connected to EL7201 used as encoder

require ecmccfg

${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=5, HW_DESC=EL7201"
epicsEnvSet("ECMC_EC_SLAVE_NUM_ENCODER",      "$(ECMC_EC_SLAVE_NUM)")


${SCRIPTEXEC} ${ecmccfg_DIR}configureSlave.cmd, "SLAVE_ID=7, HW_DESC=iPOS8020BX, CONFIG=-Motor-McLennan-34HT18C340-Parallel"
epicsEnvSet("ECMC_EC_SLAVE_NUM_DRIVE",        "$(ECMC_EC_SLAVE_NUM)")

## AXIS 1: Scaling in mm (10mm/rev)
#
epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) ($(ecmccfg_DIR)configureAxis.cmd, CONFIG=./cfg/ipos8020_1_resolver_mm.ax)

