###############################################################################
#-d /**
#-d   \brief Example script of EL6022 (2 channel RS422/485)
#-d   \details Example shows how to read and write byte data over RS422/485 (EL6022).
#-d   
#-d   \author Anders Sandstroem
#-d   \file
#-d */
#-  
#- Write Data (send "CMD_TO_SEND" over RS422/485):
#- NOTE: Max length is 22bytes at the time (can be extended)
#- 1. caput  -a IOC_TEST:m0s011-Ch01-ArrayOut <bytes> <value>
#-    caput  -a IOC_TEST:m0s011-Ch01-ArrayOut 5 1 2 3 4 5
#-
#- Read data (the IOC_TEST:m0s011-Ch01-ArrayIn will be updated for each new value available in the terminal):
#- 1. camonitor IOC_TEST:m0s011-Ch01-ArrayIn
#- (2. Several records showing status are available)
#-
#- A simple test can be done by wire a loopback connection on the DB9:
#-  1. Bridge 2 and 3
#-  2. Bridge 7 and 8
#-
#- Epics records are linked to below variables in plc code:
#- static.outBytes      : Number of bytes to write (this is done aurmatically when write to ArrayOut waveform)
#- static.InBytes       : Number of avialble bytes to read
#- static.triggWrite;   : Trigg write of data by rising edge (this is done aurmatically when write to ArrayOut waveform)
#- static.triggRead;    : Trigger New read of data. (manual triggering of next read is needed in this example)
#-

##############################################################################
require ecmccfg



#- Configure EL6022 with custom database and config of SDOs
${SCRIPTEXEC} ${ecmccfg_DIR}addSlave.cmd, "SLAVE_ID=11, HW_DESC=EL6022, SUBST_FILE=ecmcEL6022_bytes.substitutions"
epicsEnvSet(ECMC_EC_SDO_INDEX, "0x8000")  # To set correct sdo address in sensor config
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL6022-Sensor-chX-default.cmd

epicsEnvSet(ECMC_EC_SDO_INDEX, "0x8010")  # To set correct sdo address in sensor config
${SCRIPTEXEC} ${ecmccfg_DIR}ecmcEL6022-Sensor-chX-default.cmd

ecmcConfig "EcGetMemMapId(ec0.s11.mm.inputDataArray01)"
epicsEnvSet(MM_CH_1_IN,${ECMC_CONFIG_RETURN_VAL})

ecmcConfig "EcGetMemMapId(ec0.s11.mm.inputDataArray02)"
epicsEnvSet(MM_CH_2_IN,${ECMC_CONFIG_RETURN_VAL})

$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=0, SAMPLE_RATE_MS=10,FILE=./plc/el6022.plc, PLC_MACROS='PLC_ID=0,SLAVE_ID=$(ECMC_EC_SLAVE_NUM),CH_ID=01,MM_ID=${MM_CH_1_IN},DBG='")

$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=1, SAMPLE_RATE_MS=10,FILE=./plc/el6022.plc, PLC_MACROS='PLC_ID=1,SLAVE_ID=$(ECMC_EC_SLAVE_NUM),CH_ID=02,MM_ID=${MM_CH_2_IN},DBG='")

