##############################################################################
## Example: Configuraftion for running ecmc PLC without ethercat bus support
## Set MASTER_ID to -1 at call of startup.cmd
##############################################################################

require ecmccfg "MASTERID=-1"

# No EtherCAT hardware..

# AXIS 1:
epicsEnvSet("DEV",      "$(IOC)")
$(SCRIPTEXEC) $(ecmccfg_DIR)configureVirtualAxis.cmd, CONFIG=./cfg/linear_1.vax
$(SCRIPTEXEC) $(ecmccfg_DIR)applyAxisSynchronization.cmd, CONFIG=./cfg/linear_1.sax

# Data Storage 1:
$(SCRIPTEXEC) $(ecmccfg_DIR)addDataStorage.cmd "DS_ID=1, DS_SIZE=100, SAMPLE_RATE_MS=-1, DS_TYPE=2"

# PLC 0:
$(SCRIPTEXEC) $(ecmccfg_DIR)loadPLCFile.cmd, "PLC_ID=0, SAMPLE_RATE_MS=1000,FILE=./plc/plc_no_ec.plc, PLC_MACROS='PLC_ID=0,DBG='"
dbLoadRecords("ecmcPlcAnalog.db","P=$(IOC):,PORT=MC_CPU1,ASYN_NAME=plcs.plc0.static.test,REC_NAME=-Test,TSE=0,T_SMP_MS=1000")
